steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-node@v1
    with:
      node-version: 'lts/*'
  - run: npm install
  - run: npm test
  - run: npm run build
  - name: Semantic Releaser
    uses: brpaz/action-semantic-release@v1
